### ISSUE TITLE
Null value for $.viewer.message_threads.sync_sequence_id

### ISSUE THREAD

**Issue by paulguy** [dequis/purple-facebook#306]
## ADMIN EDIT

**This is already fixed in the latest release. This ticket is only open for visibility**

**Get the latest version from here https://github.com/dequis/purple-facebook/releases**

----

### Original ticket description

Connection was lost earlier today.  Reconnecting results in immediately disconnecting with `Null value for $.viewer.message_threads.sync_sequence_id`.

pidgin/libpurple 1.12.0
purple-facebook 0.9.0-c9b74a765767

**Comment by scrad** [comment]
I'm getting this error as well 

Windows 8.1
Pidgin 2.10.11 (libpurple 2.10.11)
purple-facebook Version: 20161121~a157645~c9b74a765767~117

**Comment by SarcasmCupcakes** [comment]
All morning. Even upgraded Pidgin and re-installed the two .dll files.

**Comment by drainx85** [comment]
Just happened to me as well when I logged in to my pc this evening. Wonder what facebook changed this time...

**Comment by jh-maeng** [comment]
I'm getting same error.

A few logs below:

(10:33:57) http: releasing a socket: 0E67C758
(10:33:57) http: Request 02396618 performed successfully.
(10:33:57) facebook: HTTP Response (02396618):
(10:33:57) facebook:   Response Error: 200
(10:33:57) facebook:   Response Data: {"viewer":{"message_threads":{"count":9,"mute_until":0,"nodes":[],"page_info":{"has_next_page":true},"sync_sequence_id":null,"unread_count":0,"unseen_count":0}}}
(10:33:57) facebook: Parsing JSON: {"viewer":{"message_threads":{"count":9,"mute_until":0,"nodes":[],"page_info":{"has_next_page":true},"sync_sequence_id":null,"unread_count":0,"unseen_count":0}}}

(10:33:57) connection: Connection error on 0E49FD90 (reason: 0 description: Null value for $.viewer.message_threads.sync_sequence_id)
(10:33:57) http: destroying socket: 0E67C758
(10:33:57) account: Disconnecting account savage69kr@gmail.com (02356C00)
(10:33:57) connection: Disconnecting connection 0E49FD90
(10:33:57) facebook: Writing 14 (flags: 0x0)
(10:33:57) facebook:   00000000  e0 00                                             |..|
(10:33:57) facebook:   00000010

**Comment by skolskoly** [comment]
This isn't a random glitch, it looks like facebook has decided to stop supporting old versions of the messenger app. I guess purple-facebook was based on the old protocol. Seems like we're out of luck until things are ported over.

**Comment by advcomp2019** [comment]
The weird thing is my messenger is still working just fine. I am kinda wondering one thing. Does any of you use mobile device and did it get an update? Just trying to figure this out might not be fun maybe.

**Comment by aeridus** [comment]
Same here, and I don't use the mobile app. I updated Pidgin and still see the same error.

**Comment by advcomp2019** [comment]
That rules that out then.

**Comment by Steap** [comment]
I can confirm this on Debian GNU/Linux, with Pidgin/libpurple 2.12 and purple-facebook a15764504022aa5d3fd243f5e27902e2a61f977c .

**Comment by auscompgeek** [comment]
I suspect this has something to do with Facebook dropping support for ancient versions of Messenger: https://messengerblog.com/general-messenger/update-on-support-for-older-versions-of-messenger-and-facebook-apps/

**Comment by starndust31** [comment]
Just came to say that I have the same problem

**Comment by alexolog** [comment]
Getting the same error here.
And people are reporting it on [bitllbee](https://github.com/bitlbee/bitlbee-facebook/issues/130)

**Comment by Yionel** [comment]
Same problem for me
$ lsb_release -d
Description:	Ubuntu 16.10
$ pidgin -v
Pidgin 2.10.12 (libpurple 2.10.12)
$ uname -a
Linux x220 4.8.0-42-generic #45-Ubuntu SMP Wed Mar 8 20:06:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by paulguy** [comment]
Just randomly got a few messages then something like "couldn't mark messages as received" or something along those lines then the same disconnection error again.

I had been noticing a lot of double or triple messages in the past month or so, so maybe there had been some odd breakages that had been going unnoticed for a while.

**Comment by rajcze** [comment]
Having the same issue, Pidgin 2.11.0-1.fc24 (libpurple 2.11.0), purple-facebook-0.9.0-c9b74a765767 (compiled from git)

**Comment by anecznik** [comment]
I have the same problem 

DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Pidgin 2.10.12 (libpurple 2.10.12)

but my sister have windows 8.1 and Pidgin 2.11.0 (libpurple 2.11.0) and it's work.

**Comment by dequis** [comment]
Cross-posting from https://github.com/bitlbee/bitlbee-facebook/issues/138#issuecomment-290010091

>well, fuck

**Comment by mfaerevaag** [comment]
+1

Arch Linux 4.10.6-1-ARCH x86_64
Pidgin 2.12.0 (libpurple 2.12.0)
purple-facebook 0.9.0-1

**Comment by mattlog** [comment]
Same here

Windows 7 64bit
Pidgin 2.12.0

**Comment by dequis** [comment]
Fix: https://github.com/dequis/purple-facebook/releases/tag/v0.9.1-c9b74a765767

**Comment by freddysdad** [comment]
fix allows connection/login but when sending a message says "failed to send message"

**Comment by kalab-oto** [comment]
for me also fix login, but after successful login its instantly disconected (can see contacts for second):
> Arguments are invalid

I had two phase verification (SMS), but I disable it for testing it. Also I approve device login on FB webpage.

**Comment by freddysdad** [comment]
I fixed arguments are invalid by disabling "mark messages as read" , "show self messages" , "show unread messages" , "open new group chats with incoming messages" - although I can't be sure which made it work

**Comment by Metalhead33** [comment]
In addition to disconnecting because `failed to send message`, it also fails to reconnect saying `Arguments are invalid`, and when I receive a message, it's `Failed to mark read`

**Comment by freddysdad** [comment]
receiving messages works OK with "mark messages as read" disabled

**Comment by darkmanek** [comment]
+1
Manjaro 4.10.6-1-ck-pentm i686
Pidgin 2.12.0 (libpurple 2.12.0)
purple-facebook 0.9.0-1

[purple-debug.txt](https://github.com/dequis/purple-facebook/files/878653/purple-debug.txt)

**Comment by jcengelsen** [comment]
Same problem : 

$ lsb_release -d
Description:	Linux Mint 18 Sarah
$ pidgin -v
Pidgin 2.10.12 (libpurple 2.10.12)
$ uname -a
Linux ThinkPad-T530 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LunaSquee** [comment]
Getting this as well
Arch Linux
Pidgin 2.12.0 (libpurple 2.12.0)
Linux EvertLaptop 4.10.4-1-ARCH #1 SMP PREEMPT Sat Mar 18 19:39:18 CET 2017 x86_64 GNU/Linux

**Comment by marsjaninzmarsa** [comment]
More info:
https://github.com/bitlbee/bitlbee-facebook/issues/138#issuecomment-290037214

**Comment by buchty** [comment]
Latest update (9e4c738) cures "Null value for $.viewer.message_threads.sync_sequence_id", but lets not send anything ("failed to send message" -> disconnect), also occasional "arguments are invalid" occurs. (Pidgin 2.12.0, Ubuntu 12.04LTS,  Kernel 3.13.0-113-generic)

**Comment by norbert79** [comment]
Just a generic remark over here: As it seems Facebook has added a new functionality to its chat by adding emoticons to specific lines, above the regular emoticons handling (possibly adding the functionality to express reactions on specific texts instantly). Could this be related to the failing of sending messages as specific flag is not being used or not handled well?

**Comment by alexander-e** [comment]
After updating, I get the same error message as @buchty : "Arguments are invalid". (Ubuntu 16.04, Pidgin 2.10.12)

**Comment by buchty** [comment]
Seems like the "arguments are invalid" is related to clearing message-read flags, cause it disappears once you clear unread messages using the browser-based messenger.

**Comment by buchty** [comment]
5061391 seems to work. Flawless login, receiving, and sending so far. Great job!

**Comment by PeopleInside** [comment]
I AM using Pidgin, how to fix this issue in Pidgin?

**Comment by dequis** [comment]
Yeah everything seems to be working now, but please test.

Release with dist tarball for linux users: https://github.com/dequis/purple-facebook/releases/tag/v0.9.2-c9b74a765767

Windows users can get a new dll from the usual place, https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows

Remember to restart pidgin

**Comment by PeopleInside** [comment]
Works, thank you!

**Comment by kalab-oto** [comment]
Works, thank you very much for fast fix! :+1:

**Comment by freddysdad** [comment]
confirmed working on Linux/Pidgin

**Comment by Metalhead33** [comment]
Confirmed to work flawlessly.

**Comment by mattlog** [comment]
Works on Windows 7/Pidgin, thanks.

**Comment by SarcasmCupcakes** [comment]
Works on Windows 7! Thank you.

**Comment by dequis** [comment]
Cross posting from https://github.com/bitlbee/bitlbee-facebook/issues/138#issuecomment-290111087

---------

Here's a long-form explanation of what happened here:

As others suggested, https://messengerblog.com/general-messenger/update-on-support-for-older-versions-of-messenger-and-facebook-apps/ is indeed relevant. They deploy to production on tuesdays which is when it broke.

I was aware of this, but, as far as I knew, nothing needed updating, because it says that versions older than 5 will be discontinued but we're compatible up to version 38, mostly. I suspected the `/send_message2` method might go away, or that the "MQIsdp" connections would break (the latter are only used by the oldest bitlbee-versions). But neither of those were issues, as they seem to be used by versions newer than 5 (I tested 14 and 38 today)

Versioning in facebook is complicated, which is both good and bad. Good because it allows them to have excellent backwards compatibility (as far as they want to keep it). Bad because it's hard to understand where to draw the line on what a version means.

There were two fixes:

1. The graphql query hash to get the sequence id. Those hashes represent a textual graphql query stored in the server, and those queries are basically a way to tell the server "pick these fields from this deeply nested structure and return them with this other structure". We don't know what the exact query is, we just know the arguments and the result. Well, we don't exactly know the arguments, as evidenced by those errors some people got today. But they are discoverable with some effort.

    So my best guess is that *something* in the underlying structure of the facebook graph API changed to stop supporting old clients (likely not directly related), and this means that the field that was accessed by the old hash was no longer there. The newer hash checks a different location, or filters it differently, or who knows what, but manages to access that field successfully. It also has different arguments so I'm only using it for the sync sequence number for now, while thread listing uses the other query, because everything else just works.

2. The version string in the MQTT `CONNECT` message. This was a surprise because it was previously empty and just worked, but it's how they chose to stop old versions from sending messages. I think that was the only intended breakage, and who knows, maybe the other issue is a bug that facebook should fix. Heh. Our code also likes to disconnect too easily on almost all errors, which seems to be a successful strategy overall.

Not too bad overall. Next time we won't have the surprise version check since we're sending a version exactly where they expect it. Also, I'm happy with the approach they've taken to deprecate very old versions. This announcement sounds like they are committing to 3 years or so of support for old versions, which sounds great.

**Comment by darkmanek** [comment]
Works on Manjaro

**Comment by DinoZervos** [comment]
Working on Windows 10 & Pidgin. Thanks for the quick fix!

**Comment by dequis** [comment]
Keeping this open for visibility.

Also at this point confirmations that it works are unneeded, but I do need to know if anything broke.

**Comment by Dodger395** [comment]
I am using the latest dll located at https://dl.voidium.net/pidgin/ and I am getting a "ERROR_QUEUE_OVERFLOW" error when trying to enable the account.  This started first thing this morning.

**Comment by dequis** [comment]
@Dodger395 please open a new ticket

**Comment by scrad** [comment]
Works on windows 8.1

Thanks for the speedy fix and support.

**Comment by agent-rat** [comment]
Tested working on win7. Nice one!

**Comment by alexolog** [comment]
The new DLL still does not work for me (windows XP "POSReady 2009")

```
(21:59:13) account: Connecting to account [removed].
(21:59:13) connection: Connecting. gc = 02E02418
(21:59:13) http: Performing new request 036018A0 to graph.facebook.com.
(21:59:13) dnsquery: Performing DNS lookup for graph.facebook.com
(21:59:13) dnsquery: IP resolved for graph.facebook.com
(21:59:13) proxy: Attempting connection to 31.13.74.1
(21:59:13) proxy: Connecting to graph.facebook.com:443 with no proxy
(21:59:13) proxy: Connection in progress
(21:59:13) proxy: Connecting to graph.facebook.com:443.
(21:59:13) proxy: Connected to graph.facebook.com:443.
(21:59:13) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(21:59:13) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:13) nss: partial certificate chain
(21:59:13) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(21:59:13) certificate/x509/tls_cached: Checking for cached cert...
(21:59:13) certificate/x509/tls_cached: ...Found cached cert
(21:59:13) nss/x509: Loading certificate from C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) certificate/x509/tls_cached: Peer cert matched cached
(21:59:13) nss/x509: Exporting certificate to C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) util: Writing file C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(21:59:13) certificate: Successfully verified certificate for graph.facebook.com
(21:59:13) http: Request 036018A0 performed successfully.
(21:59:13) http: Performing new request 0384E450 to graph.facebook.com.
(21:59:13) dnsquery: Performing DNS lookup for graph.facebook.com
(21:59:13) dnsquery: IP resolved for graph.facebook.com
(21:59:13) proxy: Attempting connection to 31.13.74.1
(21:59:13) proxy: Connecting to graph.facebook.com:443 with no proxy
(21:59:13) proxy: Connection in progress
(21:59:13) proxy: Connecting to graph.facebook.com:443.
(21:59:13) proxy: Connected to graph.facebook.com:443.
(21:59:13) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(21:59:13) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:13) nss: partial certificate chain
(21:59:13) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(21:59:13) certificate/x509/tls_cached: Checking for cached cert...
(21:59:13) certificate/x509/tls_cached: ...Found cached cert
(21:59:13) nss/x509: Loading certificate from C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) certificate/x509/tls_cached: Peer cert matched cached
(21:59:13) nss/x509: Exporting certificate to C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) util: Writing file C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:13) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(21:59:13) certificate: Successfully verified certificate for graph.facebook.com
(21:59:13) http: Request 0384E450 performed successfully.
(21:59:13) dnsquery: Performing DNS lookup for mqtt.facebook.com
(21:59:13) dnsquery: IP resolved for mqtt.facebook.com
(21:59:13) proxy: Attempting connection to 157.240.2.15
(21:59:13) proxy: Connecting to mqtt.facebook.com:443 with no proxy
(21:59:13) proxy: Connection in progress
(21:59:13) proxy: Connecting to mqtt.facebook.com:443.
(21:59:13) proxy: Connected to mqtt.facebook.com:443.
(21:59:13) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(21:59:13) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:13) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:13) nss: partial certificate chain
(21:59:13) certificate/x509/tls_cached: Starting verify for mqtt.facebook.com
(21:59:13) certificate/x509/tls_cached: Checking for cached cert...
(21:59:13) certificate/x509/tls_cached: ...Found cached cert
(21:59:13) nss/x509: Loading certificate from C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(21:59:13) certificate/x509/tls_cached: Peer cert matched cached
(21:59:13) nss/x509: Exporting certificate to C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(21:59:13) util: Writing file C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\mqtt.facebook.com
(21:59:13) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(21:59:13) certificate: Successfully verified certificate for mqtt.facebook.com
(21:59:14) util: Writing file prefs.xml to directory C:\Documents and Settings\USer\Application Data\.purple
(21:59:14) util: Writing file C:\Documents and Settings\User\Application Data\.purple\prefs.xml
(21:59:14) http: Performing new request 0384E4F8 to graph.facebook.com.
(21:59:14) dnsquery: Performing DNS lookup for graph.facebook.com
(21:59:14) dnsquery: IP resolved for graph.facebook.com
(21:59:14) proxy: Attempting connection to 31.13.74.1
(21:59:14) proxy: Connecting to graph.facebook.com:443 with no proxy
(21:59:14) proxy: Connection in progress
(21:59:14) proxy: Connecting to graph.facebook.com:443.
(21:59:14) proxy: Connected to graph.facebook.com:443.
(21:59:14) nss: SSL version 3.3 using 128-bit AES-GCM with 128-bit AEAD MAC
Server Auth: 256-bit ECDSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
(21:59:14) nss: subject=CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US issuer=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:14) nss: subject=CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US issuer=CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
(21:59:14) nss: partial certificate chain
(21:59:14) certificate/x509/tls_cached: Starting verify for graph.facebook.com
(21:59:14) certificate/x509/tls_cached: Checking for cached cert...
(21:59:14) certificate/x509/tls_cached: ...Found cached cert
(21:59:14) nss/x509: Loading certificate from C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:14) certificate/x509/tls_cached: Peer cert matched cached
(21:59:14) nss/x509: Exporting certificate to C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:14) util: Writing file C:\Documents and Settings\User\Application Data\.purple\certificates\x509\tls_peers\graph.facebook.com
(21:59:14) nss: Trusting CN=*.facebook.com,O="Facebook, Inc.",L=Menlo Park,ST=California,C=US
(21:59:14) certificate: Successfully verified certificate for graph.facebook.com
(21:59:14) http: Request 0384E4F8 performed successfully.
(21:59:14) connection: Connection error on 02E02418 (reason: 0 description: Null value for $.viewer.message_threads.sync_sequence_id)
(21:59:14) account: Disconnecting account [removed] (01235618)
(21:59:14) connection: Disconnecting connection 02E02418
(21:59:14) connection: Destroying connection 02E02418
(21:59:19) util: Writing file accounts.xml to directory C:\Documents and Settings\User\Application Data\.purple
(21:59:19) util: Writing file C:\Documents and Settings\User\Application Data\.purple\accounts.xml
```

**Comment by alexolog** [comment]
Incidentally, connecting from my computer at work (Win 8.1) worked file even with the old DLL.

**Comment by dequis** [comment]
@alexolog That debug log is useless without the flags mentioned in https://github.com/dequis/purple-facebook/wiki/Debugging-Logs

Also please open a new ticket.

>Looking inside the DLL for strings I see "`20170329~5061391~c9b74a765767~124`"
Is that the latest?

Yes. Also, you can just use buddy list -> help menu -> plugin information

**Comment by alexolog** [comment]
Log emailed.  Thanks.

**Comment by dcarriger90** [comment]
Working for me on windows 10 after replacing dlls. Thanks.

**Comment by DnR-iData** [comment]
Worked for me on Ubuntu 16.04.2 LTS, thanks a lot :)

**Comment by dezooo** [comment]
Hei guys,
pulled 3cbb433d12ba04111fd0ba3e6c86dac72cfc83a4, built and still the same error :(
Pidgin 2.11.0 (libpurple 2.11.0), debian jessie

**Comment by mtyrio** [comment]
While installing release with dist tarball for linux on Linux Mint i got an error:
```
configure: error: Package requirements (purple <  3) were not met:

No package 'purple' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```
And i can't find such package. Can someone help?

**Comment by patelkunala** [comment]
Works perfect! Would it work if I upgraded to Pidgin version 2.12 or latest?

Win7 - 64 bit
Pidgin version - 2.10.12

**Comment by advcomp2019** [comment]
@dezooo , go check in Help -> Plugin information and look for Facebook. Make sure you are using the newest version. If you don't know, you can paste it here and wait for someone to tell you.

@mtyrio , sounds like there is a path problem somewhere. I am not sure since it has been a while since I have compiled this on Linux.

@patelkunala , you can upgrade if you want, but it is best to have the newest version. It is really up

**Comment by boris-petrov** [comment]
Same with me - I get the same error with version `0.9.3-c9b74a765767` (seen in the Help -> Plugin information page). Help, I can't live without this plugin!

**Comment by dezooo** [comment]
Facebook
	Author: (null)
	Version: 0.9.3-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

**Comment by abpross** [comment]
works on Xubuntu 16.04 
Pidgin 2.10.12 (libpurple 2.10.12)

**Comment by martlin2cz** [comment]
Thanks!! Worked for me as well.

    $ uname -a
    Linux martlins 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
    $ pidgin -v
    Pidgin 2.11.0 (libpurple 2.11.0)

**Comment by dezooo** [comment]
```
(14:30:50) facebook: HTTP Response (0x7f7725c1ab00):
(14:30:50) facebook:   Response Error: 200
(14:30:50) facebook:   Response Data: {"viewer":{"message_threads":{"count":378,"mute_until":0,"nodes":[],"page_info":{"has_next_page":true},"sync_sequence_id":null,"unread_count":11,"unseen_count":0}}}
(14:30:50) facebook: Parsing JSON: {"viewer":{"message_threads":{"count":378,"mute_until":0,"nodes":[],"page_info":{"has_next_page":true},"sync_sequence_id":null,"unread_count":11,"unseen_count":0}}}
(14:30:50) connection: Connection error on 0x7f7725125e90 (reason: 0 description: Null value for $.viewer.message_threads.sync_sequence_id)
```

**Comment by jnsatterfield** [comment]
I can confirm the "Null value for $.viewer.message_threads.sync_sequence_id" error in Xubuntu with Pidgin 2.10.12.

`uname -a`
`Linux himinbjorn 4.8.0-42-generic #45-Ubuntu SMP Wed Mar 8 20:06:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`pidgin -v`
`Pidgin 2.10.12 (libpurple 2.10.12)`

**Comment by dequis** [comment]
Pidgin versions (or linux kernel versions) do not affect this issue so I don't need to know those.

Instead, please check the version of this plugin in buddy list -> help menu -> plugin information.

Also, there was another release since my last comment, 0.9.3, appears to fix some more issues: https://github.com/dequis/purple-facebook/releases

Depending on the way it was built, that version might appear as 20170330[...]

**Comment by jnsatterfield** [comment]
Facebook
	Author: (null)
	Version: 0.9.0-c9b74a765767
	Website: https://github.com/dequis/purple-facebook
	ID String: prpl-facebook
	Loadable: Yes
	Loaded: Yes

I'll go grab 0.9.3 and report the differential.

**Comment by jnsatterfield** [comment]
:+1: 
After cloning version 0.9.3 and building/installing, the `Null value for $.viewer.message_threads.sync_sequence_id` issue seems to be resolved.

**Comment by dezooo** [comment]
SOLVED!
make clean && make
is not enough! something is not rebuilt!
If I cloned a fresh copy and built it, it works!

Sorry for error reports.

**Comment by marmz** [comment]
+1
Same error message, from today...
Using **pidgin + libpurple-dev** from **OFFICIAL** Debian Jessie **STABLE** repositories.

I hope i don't have to compile sources to get it back working .. ;)

**Comment by rfc1036** [comment]
Even after a `make distclean`, I had to run again `update.sh` to build a working pluing. HTH.

**Comment by paulguy** [comment]
I was able to get it to rebuild just fine with `git reset --hard` then running `./autogen.sh`.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
Thank you very much, dequis. Works like a charm on Ubuntu Pidgin.

**Comment by karbon15** [comment]
Thanks indeed, dequis!  Works as well with the spectrum2 transport.

**Comment by mandree** [comment]
For me, on a Git checkout, it also took `./update.sh` and `autogen.sh` before I could build a working version. Just "git pull" isn't sufficient.

**Comment by grzegorz-janoszka** [comment]
When can we have updated windows builds?

**Comment by auscompgeek** [comment]
> When can we have updated windows builds?

The Windows build is automatically built and updated on every commit by Travis CI.

**Comment by grzegorz-janoszka** [comment]
Ah, indeed. I was mistaken by exactly the same file length (and no version number). Indeed the windows build has been fixed.

**Comment by TheFoggyRoad** [comment]
i tried the download from: https://github.com/dequis/purple-facebook/wiki/Installing-on-Windows
As well as downloading the new package from chocolatey: cup purple-facebook --version=0.9.3.126

I am still getting the "Null value for $.viewer.message_threads.sync_sequence_id" error. I am on the newest version of Pidgin. What should I do?

**Comment by dequis** [comment]
@TheFoggyRoad please open a new issue

Also, verify the version of the plugin in buddy list -> help menu -> plugin information. Depending on the way it was built, that version might appear as 20170330[...]

**Comment by dequis** [comment]
I'm locking this thread since this is resolved.

If anyone has any issues please open a new issue instead.
